import pandas as pd

data = {
    'Q1': ['Research Papers/PDFs', 'Watching YouTube Videos', 'using AI Tools', 'Visual/Diagramatic Representations','Research Papers/PDFs', 'Watching YouTube Videos', 'using AI Tools', 'Visual/Diagramatic Representations','Research Papers/PDFs', 'Watching YouTube Videos', 'using AI Tools', 'Visual/Diagramatic Representations','Research Papers/PDFs', 'Watching YouTube Videos', 'using AI Tools', 'Visual/Diagramatic Representations','Research Papers/PDFs', 'Watching YouTube Videos', 'using AI Tools', 'Visual/Diagramatic Representations','Research Papers/PDFs', 'Watching YouTube Videos', 'using AI Tools', 'Visual/Diagramatic Representations'],
    'Q2': ['Watching video lectures', 'Reading textbooks', 'Performing Practicals', 'Learning concepts by heart','Watching video lectures', 'Reading textbooks', 'Performing Practicals', 'Learning concepts by heart','Watching video lectures', 'Reading textbooks', 'Performing Practicals', 'Learning concepts by heart','Watching video lectures', 'Reading textbooks', 'Performing Practicals', 'Learning concepts by heart','Watching video lectures', 'Reading textbooks', 'Performing Practicals', 'Learning concepts by heart','Watching video lectures', 'Reading textbooks', 'Performing Practicals', 'Learning concepts by heart'],
    'Q3': ['Textbooks', 'Handwritten Notes', 'AI Tools', 'Videos & Podcasts','Textbooks', 'Handwritten Notes', 'AI Tools', 'Videos & Podcasts','Textbooks', 'Handwritten Notes', 'AI Tools', 'Videos & Podcasts','Textbooks', 'Handwritten Notes', 'AI Tools', 'Videos & Podcasts','Textbooks', 'Handwritten Notes', 'AI Tools', 'Videos & Podcasts','Textbooks', 'Handwritten Notes', 'AI Tools', 'Videos & Podcasts'],
    'Q4': ['Reading it several times', 'Repeating key points in mind or aloud', 'Associating it with real life examples', 'Writing it down in a summary','Reading it several times', 'Repeating key points in mind or aloud', 'Associating it with real life examples', 'Writing it down in a summary','Reading it several times', 'Repeating key points in mind or aloud', 'Associating it with real life examples', 'Writing it down in a summary','Reading it several times', 'Repeating key points in mind or aloud', 'Associating it with real life examples', 'Writing it down in a summary','Reading it several times', 'Repeating key points in mind or aloud', 'Associating it with real life examples', 'Writing it down in a summary','Reading it several times', 'Repeating key points in mind or aloud', 'Associating it with real life examples', 'Writing it down in a summary'],
    'Q5': ['Writing detailed paragraph', 'Creating bullet points', 'Diagramatic representation of concepts', 'Making mindmaps','Writing detailed paragraph', 'Creating bullet points', 'Diagramatic representation of concepts', 'Making mindmaps','Writing detailed paragraph', 'Creating bullet points', 'Diagramatic representation of concepts', 'Making mindmaps','Writing detailed paragraph', 'Creating bullet points', 'Diagramatic representation of concepts', 'Making mindmaps','Writing detailed paragraph', 'Creating bullet points', 'Diagramatic representation of concepts', 'Making mindmaps','Writing detailed paragraph', 'Creating bullet points', 'Diagramatic representation of concepts', 'Making mindmaps'],
    'Q6': ['Design visual slides', 'Practice aloud with friends', 'Write a detailed script', 'Simulate it in real life','Design visual slides', 'Practice aloud with friends', 'Write a detailed script', 'Simulate it in real life','Design visual slides', 'Practice aloud with friends', 'Write a detailed script', 'Simulate it in real life','Design visual slides', 'Practice aloud with friends', 'Write a detailed script', 'Simulate it in real life','Design visual slides', 'Practice aloud with friends', 'Write a detailed script', 'Simulate it in real life','Design visual slides', 'Practice aloud with friends', 'Write a detailed script', 'Simulate it in real life'],
    'Q7': ['YouTube Videos', 'AI Tools', 'Group Study', 'Books','YouTube Videos', 'AI Tools', 'Group Study', 'Books','YouTube Videos', 'AI Tools', 'Group Study', 'Books','YouTube Videos', 'AI Tools', 'Group Study', 'Books','YouTube Videos', 'AI Tools', 'Group Study', 'Books','YouTube Videos', 'AI Tools', 'Group Study', 'Books'],
    'Q8': ['Digital notes in PDF', 'Aesthetic handwritten notes with doodles', 'Typing quick bullet points on Notes App', 'Screenshots or photos of important info','Digital notes in PDF', 'Aesthetic handwritten notes with doodles', 'Typing quick bullet points on Notes App', 'Screenshots or photos of important info','Digital notes in PDF', 'Aesthetic handwritten notes with doodles', 'Typing quick bullet points on Notes App', 'Screenshots or photos of important info','Digital notes in PDF', 'Aesthetic handwritten notes with doodles', 'Typing quick bullet points on Notes App', 'Screenshots or photos of important info','Digital notes in PDF', 'Aesthetic handwritten notes with doodles', 'Typing quick bullet points on Notes App', 'Screenshots or photos of important info','Digital notes in PDF', 'Aesthetic handwritten notes with doodles', 'Typing quick bullet points on Notes App', 'Screenshots or photos of important info'],
    'learning_style': ['Visual Voyager', 'Stream Hustler', 'Logic Maverick', 'Collaborative Learner', 'Active Techie', 'Solo Sage','Visual Voyager', 'Stream Hustler', 'Logic Maverick', 'Collaborative Learner', 'Active Techie', 'Solo Sage', 'Visual Voyager', 'Stream Hustler', 'Logic Maverick', 'Collaborative Learner', 'Active Techie', 'Solo Sage', 'Visual Voyager', 'Stream Hustler', 'Logic Maverick', 'Collaborative Learner', 'Active Techie', 'Solo Sage']
}

df = pd.DataFrame(data)
df.to_csv('learning_data.csv', index=False)
print("CSV file created successfully.")